In [1]:
import numpy as np

In [2]:
# sort method 

In [3]:
a = np.random.randint(1,100,15)
a

array([24, 74,  2, 71, 49, 84, 38, 44,  6, 17, 46,  6, 73, 30, 72])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 7, 94, 74, 91],
       [28, 62, 80, 69],
       [70, 62, 39, 83],
       [80, 31, 24, 81],
       [58, 37, 58, 72],
       [17, 61,  7, 27]])

In [5]:
np.sort(a)

array([ 2,  6,  6, 17, 24, 30, 38, 44, 46, 49, 71, 72, 73, 74, 84])

In [6]:
# np.sort(array , axis ,kind)
np.sort(b) # by default row wise sort karta ha

array([[ 7, 74, 91, 94],
       [28, 62, 69, 80],
       [39, 62, 70, 83],
       [24, 31, 80, 81],
       [37, 58, 58, 72],
       [ 7, 17, 27, 61]])

In [7]:
np.sort(b,axis=0)  # column wise sorted 

array([[ 7, 31,  7, 27],
       [17, 37, 24, 69],
       [28, 61, 39, 72],
       [58, 62, 58, 81],
       [70, 62, 74, 83],
       [80, 94, 80, 91]])

In [8]:
#  for descending 
np.sort(a)[::-1]

array([84, 74, 73, 72, 71, 49, 46, 44, 38, 30, 24, 17,  6,  6,  2])

In [9]:
# append method

In [10]:
np.append(a,150)

array([ 24,  74,   2,  71,  49,  84,  38,  44,   6,  17,  46,   6,  73,
        30,  72, 150])

In [11]:
np.append(b , np.ones((b.shape[0],1)),axis=1)

array([[ 7., 94., 74., 91.,  1.],
       [28., 62., 80., 69.,  1.],
       [70., 62., 39., 83.,  1.],
       [80., 31., 24., 81.,  1.],
       [58., 37., 58., 72.,  1.],
       [17., 61.,  7., 27.,  1.]])

In [12]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[ 7.        , 94.        , 74.        , 91.        ,  0.94790028],
       [28.        , 62.        , 80.        , 69.        ,  0.39862529],
       [70.        , 62.        , 39.        , 83.        ,  0.52222551],
       [80.        , 31.        , 24.        , 81.        ,  0.95074582],
       [58.        , 37.        , 58.        , 72.        ,  0.22336404],
       [17.        , 61.        ,  7.        , 27.        ,  0.54238881]])

In [13]:
# Concatenate method

In [14]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
# Unique method 

In [18]:
arr_dup = np.array([1,1,2,2,3,4,3,4,5,6,5,7,6,7,8,9,8])
np.unique(arr_dup)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# expand_dims method

In [20]:
a.shape

(15,)

In [21]:
np.expand_dims(a,axis=0)

array([[24, 74,  2, 71, 49, 84, 38, 44,  6, 17, 46,  6, 73, 30, 72]])

In [22]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [23]:
np.expand_dims(a,axis=1)

array([[24],
       [74],
       [ 2],
       [71],
       [49],
       [84],
       [38],
       [44],
       [ 6],
       [17],
       [46],
       [ 6],
       [73],
       [30],
       [72]])

In [24]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [25]:
# where method 

In [26]:
x = np.array([1,20,34,56,67,78,33,23,29,55,89,99,100])
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [27]:
# find all the indices with value greator than 50.
np.where(x>50)

(array([ 3,  4,  5,  9, 10, 11, 12], dtype=int64),)

In [28]:
# replace all values > 50 with 0.
# syntax (condition,true,false)
np.where(x>50,0,x)

array([ 1, 20, 34,  0,  0,  0, 33, 23, 29,  0,  0,  0,  0])

In [29]:
# replace all the even numbers with 0 .
np.where(x%2 == 0 , 0 ,x)

array([ 1,  0,  0,  0, 67,  0, 33, 23, 29, 55, 89, 99,  0])

In [30]:
# argmax method 

In [31]:
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [32]:
# The numpy.argmax() function returns indices of the max element of the array in a particular axis.
np.argmax(x) 

12

In [33]:
b

array([[ 7, 94, 74, 91],
       [28, 62, 80, 69],
       [70, 62, 39, 83],
       [80, 31, 24, 81],
       [58, 37, 58, 72],
       [17, 61,  7, 27]])

In [34]:
np.argmax(b,axis=0)

array([3, 0, 1, 0], dtype=int64)

In [35]:
np.argmax(b,axis=1)

array([1, 2, 3, 3, 3, 1], dtype=int64)

In [36]:
# argmin method

In [37]:
np.argmin(b,axis=0)

array([0, 3, 5, 5], dtype=int64)

In [38]:
# cumsum method (cumulative sum method)

In [39]:
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [40]:
np.cumsum(x)

array([  1,  21,  55, 111, 178, 256, 289, 312, 341, 396, 485, 584, 684])

In [41]:
b

array([[ 7, 94, 74, 91],
       [28, 62, 80, 69],
       [70, 62, 39, 83],
       [80, 31, 24, 81],
       [58, 37, 58, 72],
       [17, 61,  7, 27]])

In [42]:
np.cumsum(b,axis=0) #column 

array([[  7,  94,  74,  91],
       [ 35, 156, 154, 160],
       [105, 218, 193, 243],
       [185, 249, 217, 324],
       [243, 286, 275, 396],
       [260, 347, 282, 423]])

In [43]:
np.cumsum(b,axis=1) #row

array([[  7, 101, 175, 266],
       [ 28,  90, 170, 239],
       [ 70, 132, 171, 254],
       [ 80, 111, 135, 216],
       [ 58,  95, 153, 225],
       [ 17,  78,  85, 112]])

In [44]:
# cumprod method

In [45]:
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [46]:
np.cumprod(x)

array([          1,          20,         680,       38080,     2551360,
         199006080, -2022733952,   721759360,  -543815040,   154943872,
         905102720,  -589143936,  1215148544])

In [47]:
b

array([[ 7, 94, 74, 91],
       [28, 62, 80, 69],
       [70, 62, 39, 83],
       [80, 31, 24, 81],
       [58, 37, 58, 72],
       [17, 61,  7, 27]])

In [48]:
np.cumprod(b,axis=0)

array([[          7,          94,          74,          91],
       [        196,        5828,        5920,        6279],
       [      13720,      361336,      230880,      521157],
       [    1097600,    11201416,     5541120,    42213717],
       [   63660800,   414452392,   321384960, -1255579672],
       [ 1082233600,  -488207864, -2045272576,   459087224]])

In [49]:
np.cumprod(b,axis=1)

array([[       7,      658,    48692,  4430972],
       [      28,     1736,   138880,  9582720],
       [      70,     4340,   169260, 14048580],
       [      80,     2480,    59520,  4821120],
       [      58,     2146,   124468,  8961696],
       [      17,     1037,     7259,   195993]])

In [50]:
# percentile method

In [51]:
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [52]:
np.percentile(x,100)

100.0

In [53]:
np.percentile(x,0)

1.0

In [54]:
np.percentile(x,50)

55.0

In [55]:
np.median(x)

55.0

In [56]:
b

array([[ 7, 94, 74, 91],
       [28, 62, 80, 69],
       [70, 62, 39, 83],
       [80, 31, 24, 81],
       [58, 37, 58, 72],
       [17, 61,  7, 27]])

In [57]:
np.percentile(b,50,axis=0)

array([43. , 61.5, 48.5, 76.5])

In [58]:
np.percentile(b,50,axis=1)

array([82.5, 65.5, 66. , 55.5, 58. , 22. ])

In [59]:
# histogram method

In [60]:
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [61]:
np.histogram(x,bins=[0,20,40,60,80,100])

(array([1, 5, 2, 2, 3], dtype=int64), array([  0,  20,  40,  60,  80, 100]))

In [62]:
# corrcoef method(Correlation Coefficient )
# how much quantities depend on each other 

In [63]:
salary = np.array([1000,2000,3000,40000])
experience = np.array([1,2,3,4])
np.corrcoef(salary,experience)

array([[1.       , 0.8010362],
       [0.8010362, 1.       ]])

In [64]:
# salary to salary then salary to experience 
# experience to salary then experience to experience 

In [65]:
# numpy.isin() method 
# searching multiple items at a time.

In [66]:
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [67]:
items =[1,20,60,100,80]
np.isin(x,items)

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False,  True])

In [68]:
x[np.isin(x,items)]

array([  1,  20, 100])

In [69]:
# flip method

In [70]:
x

array([  1,  20,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [71]:
np.flip(x)

array([100,  99,  89,  55,  29,  23,  33,  78,  67,  56,  34,  20,   1])

In [72]:
b

array([[ 7, 94, 74, 91],
       [28, 62, 80, 69],
       [70, 62, 39, 83],
       [80, 31, 24, 81],
       [58, 37, 58, 72],
       [17, 61,  7, 27]])

In [73]:
np.flip(b,axis=0)

array([[17, 61,  7, 27],
       [58, 37, 58, 72],
       [80, 31, 24, 81],
       [70, 62, 39, 83],
       [28, 62, 80, 69],
       [ 7, 94, 74, 91]])

In [74]:
np.flip(b,axis=1)

array([[91, 74, 94,  7],
       [69, 80, 62, 28],
       [83, 39, 62, 70],
       [81, 24, 31, 80],
       [72, 58, 37, 58],
       [27,  7, 61, 17]])

In [75]:
# put method (editing) ya original array ma changes karta ha .

In [76]:
# syntax np.put(array,[index/indexes],[changes])
np.put(x,[0,1],[100,200])

In [77]:
x

array([100, 200,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [78]:
b

array([[ 7, 94, 74, 91],
       [28, 62, 80, 69],
       [70, 62, 39, 83],
       [80, 31, 24, 81],
       [58, 37, 58, 72],
       [17, 61,  7, 27]])

In [79]:
np.put(b,[4,5],[400,500])

In [80]:
b

array([[  7,  94,  74,  91],
       [400, 500,  80,  69],
       [ 70,  62,  39,  83],
       [ 80,  31,  24,  81],
       [ 58,  37,  58,  72],
       [ 17,  61,   7,  27]])

In [81]:
# delete method 

In [82]:
# syntax np.delete(array,index)
np.delete(x,0)

array([200,  34,  56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [83]:
np.delete(x,[0,1,2])

array([ 56,  67,  78,  33,  23,  29,  55,  89,  99, 100])

In [84]:
# Set Methods

In [86]:
# union1d
m = np.array([1,2,3,4,5])
n = np.array([6,7,8,9,10])
np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
# intersect1d
np.intersect1d(m,n)

array([], dtype=int32)

In [89]:
# setdiff1d
np.setdiff1d(m,n)

array([1, 2, 3, 4, 5])

In [91]:
# setxor1d
p = np.array([6,7,8,10,12])
q = np.array([13,14,6,7,8])
np.setxor1d(p,q)

array([10, 12, 13, 14])

In [93]:
# np.in1d
np.in1d(m,2)
m[np.in1d(m,2)]

array([2])

In [97]:
# np.clip method 

In [98]:
a

array([24, 74,  2, 71, 49, 84, 38, 44,  6, 17, 46,  6, 73, 30, 72])

In [99]:
np.clip(a,a_min=30,a_max=80)

array([30, 74, 30, 71, 49, 80, 38, 44, 30, 30, 46, 30, 73, 30, 72])

In [96]:
# Campusx Interview question
# np.swapaxes
# np.tile
# np.uniform
# np.count_nonzero