In [1]:
import numpy as np

In [2]:
# Creating Numpy Array(np.array)
a = np.array([1,2,3,4,5])  #vector
type(a)

numpy.ndarray

In [3]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])  #matrix
b
x= np.array([[[1,2,3],[4,5,6]]]) #tensor
x.ndim

3

In [4]:
# create array with custom datatype
# dtype
p = np.array([1,2,3,4],dtype="float")
p

array([1., 2., 3., 4.])

In [5]:
# how to change array type 
p=p.astype('int')
p

array([1, 2, 3, 4])

In [6]:
# np.arange
arr = np.arange(1,9) #last number is exclusive 
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr_2 = np.arange(10,20)
arr_2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
arr_slice = np.arange(1,16,2)
arr_slice

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [9]:
# arr_reshape = np.arange(10,30).reshape((4,5))
# arr_reshape.ndim
arr_reshape = np.arange(10,40).reshape((3,2,5))
# arr_reshape.ndim
arr_reshape

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [10]:
arr_prac = np.arange(10,70).reshape(4,3,5)
arr_prac

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54]],

       [[55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [11]:
# creating array having all ones 
arr_one = np.ones((5,5))
arr_one  # it returns array in a float datatype.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# creating null array
null_arr = np.zeros((5,5),dtype='int')
null_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
# there are three methods to initialize n array
# 1- np.ones 2- np.zeros 3- np.random

In [14]:
# np.random
# it create an array with a range of 0 to 1.
arr_random = np.random.random((3,4))
arr_random

array([[0.29582848, 0.77889885, 0.0881889 , 0.26857535],
       [0.6530038 , 0.77512245, 0.61050359, 0.81256771],
       [0.30063447, 0.88525479, 0.14497164, 0.39240249]])

In [15]:
# np.linspace (linear space)
# it takes three arguments(range,how much distance)
arr_linear = np.linspace(1,10,5)
arr_linear

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
arr_linear_2 = np.linspace(10,30,10)
arr_linear_2 

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

In [17]:
# np.identity
arr_identity = np.identity(2,dtype='int')
arr_identity

array([[1, 0],
       [0, 1]])

In [18]:
# Numpy attributes 
# ndim,shape,size,itemsize,dtype

In [19]:
arr_attributes = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
arr_attributes =  arr_attributes.astype('float')
arr_attributes

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [20]:
# ndim
arr_attributes.ndim

2

In [21]:
# shape
arr_attributes.shape

(2, 5)

In [22]:
# size
arr_attributes.size

10

In [23]:
# itemsize
# integer32 take 4 bytes and integer64 take 8 bytes(integer64 is by default)
arr_attributes.itemsize  #bytes 

8

In [24]:
# dtype
arr_attributes.dtype

dtype('float64')

In [25]:
# astype
# arr.astype(np.int32)

In [26]:
# Array Operations 

In [27]:
# scalar and vector operations 

In [28]:
arr_attributes

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [29]:
arr_attributes + 2

array([[ 3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12.]])

In [30]:
arr2_attributes = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(2,5).astype('float')
arr2_attributes

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [31]:
arr_attributes

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [32]:
arr2_attributes

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [33]:
result = arr_attributes + arr2_attributes
result

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.]])

In [34]:
# Array functions 

In [35]:
arr = np.random.random((3,3))
arr = np.round(arr*100)
arr

array([[92., 58., 23.],
       [87., 80., 10.],
       [81., 85., 33.]])

In [36]:
# max/min/sum/product

In [37]:
np.max(arr)

92.0

In [38]:
np.min(arr)

10.0

In [39]:
np.sum(arr)

549.0

In [40]:
np.prod(arr)

1940755300704000.0

In [41]:
# find max element in each column and row.
each_row =  np.max(arr,axis=1)
each_row

array([92., 87., 85.])

In [42]:
each_column = np.max(arr,axis=0)
each_column

array([92., 85., 33.])

In [43]:
# find min element of each row and column 
arr_min = np.arange(10,30).reshape(5,4)
arr_min

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [44]:
row = np.min(arr_min,axis=1)
row

array([10, 14, 18, 22, 26])

In [45]:
col = np.min(arr_min,axis=0)
col

array([10, 11, 12, 13])

In [46]:
# find product of each col and row 
col = np.product(arr_min,axis=0)
col

array([1441440, 1946835, 2580480, 3364725])

In [47]:
row = np.product(arr_min,axis=1)
row

array([ 17160,  57120, 143640, 303600, 570024])

In [48]:
# mean/median/std/var

In [49]:
np.mean(arr_min)

19.5

In [50]:
np.median(arr_min)

19.5

In [51]:
np.std(arr_min,axis=0)

array([5.65685425, 5.65685425, 5.65685425, 5.65685425])

In [52]:
np.var(arr_min,axis=1)

array([1.25, 1.25, 1.25, 1.25, 1.25])

In [53]:
# Trignometric Functions

In [54]:
np.cos(arr_min)

array([[-0.83907153,  0.0044257 ,  0.84385396,  0.90744678],
       [ 0.13673722, -0.75968791, -0.95765948, -0.27516334],
       [ 0.66031671,  0.98870462,  0.40808206, -0.54772926],
       [-0.99996083, -0.53283302,  0.42417901,  0.99120281],
       [ 0.64691932, -0.29213881, -0.96260587, -0.74805753]])

In [55]:
np.sin(arr_min)

array([[-0.54402111, -0.99999021, -0.53657292,  0.42016704],
       [ 0.99060736,  0.65028784, -0.28790332, -0.96139749],
       [-0.75098725,  0.14987721,  0.91294525,  0.83665564],
       [-0.00885131, -0.8462204 , -0.90557836, -0.13235175],
       [ 0.76255845,  0.95637593,  0.27090579, -0.66363388]])

In [56]:
# dot product

In [57]:
array_1 = np.arange(1,21).reshape(4,5)
array_2 = np.arange(20,40).reshape(5,4)

In [58]:
array_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
array_2

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [60]:
np.dot(array_1,array_2)

array([[ 460,  475,  490,  505],
       [1160, 1200, 1240, 1280],
       [1860, 1925, 1990, 2055],
       [2560, 2650, 2740, 2830]])

In [61]:
# log and exponents

In [62]:
np.log(array_1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ],
       [2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227]])

In [63]:
np.exp(array_2)

array([[4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11],
       [1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13],
       [7.89629602e+13, 2.14643580e+14, 5.83461743e+14, 1.58601345e+15],
       [4.31123155e+15, 1.17191424e+16, 3.18559318e+16, 8.65934004e+16]])

In [64]:
# round, floor and ceil
arr_new = np.arange(34,64).reshape(5,6).astype('float')
np.round(arr_new*100)

array([[3400., 3500., 3600., 3700., 3800., 3900.],
       [4000., 4100., 4200., 4300., 4400., 4500.],
       [4600., 4700., 4800., 4900., 5000., 5100.],
       [5200., 5300., 5400., 5500., 5600., 5700.],
       [5800., 5900., 6000., 6100., 6200., 6300.]])

In [65]:
# floor ---> 9.2 = 9
np.floor(arr_new)

array([[34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45.],
       [46., 47., 48., 49., 50., 51.],
       [52., 53., 54., 55., 56., 57.],
       [58., 59., 60., 61., 62., 63.]])

In [66]:
# ceil ---> 9.2 = 10
np.ceil(arr_new)

array([[34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45.],
       [46., 47., 48., 49., 50., 51.],
       [52., 53., 54., 55., 56., 57.],
       [58., 59., 60., 61., 62., 63.]])

In [67]:
# Indexing and slicing 

In [68]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [69]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [72]:
a1[9]

9

In [73]:
a2[1][3]

7

In [74]:
a3[1][1][1]

7

In [75]:
# for last element [-1]

In [76]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
a3[1,1,1]

7

In [78]:
a3[1,0,1]

5

In [79]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
a1[2:5]

array([2, 3, 4])

In [81]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a2[0, :]

array([0, 1, 2, 3])

In [83]:
a2[:,2]

array([ 2,  6, 10])

In [84]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [85]:
# grab 0,3,8,11 from array(a2)

In [86]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [88]:
# grab 1,3,9,11

In [89]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [90]:
# grab 4,7
a2[1:2,::3]

array([[4, 7]])

In [91]:
# grab 1,2,3 and 5,6,7

In [92]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [93]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
# grab 1,7,8

In [95]:
a2[[0,1,2],[1,3,0]]

array([1, 7, 8])

In [96]:
# grab 0,7,4,8,10

In [97]:
row_indices = np.array([0,1,1,2,2])
col_indices = np.array([0,0,3,0,2])
a2[row_indices,col_indices]

array([ 0,  4,  7,  8, 10])

In [98]:
a2[[0,1,1,2,2],[0,0,3,0,2]]

array([ 0,  4,  7,  8, 10])

In [99]:
# a3
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [100]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [101]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
# grab 3,4,5

In [103]:
a3[0][1]

array([3, 4, 5])

In [104]:
a3[0:1,1]

array([[3, 4, 5]])

In [105]:
# grab 10,13,16

In [106]:
a3[1:2,:,1:2]

array([[[10],
        [13],
        [16]]])

In [107]:
# grab 22,23 and 25,26

In [108]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [109]:
# grab 0,2 and 18,20

In [110]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [111]:
# array Iterations

In [112]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
for element in np.nditer(a1):
    print(element)

0
1
2
3
4
5
6
7
8
9


In [116]:
for i in np.nditer(a3):
    print(i+10,end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 

In [117]:
# Reshaping

In [118]:
# reshape,transpose,ravel

In [119]:
# transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [120]:
# Ravel (convert the higher dimensions array into single dimension)
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [121]:
# Stacking 
# Horizontal stacking
# Vertical stacking
# CONDITION : shape must be same. 

In [122]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [123]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [126]:
# hstack
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [127]:
# vstack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [129]:
# splitting
# horizontal
# vertical

In [130]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
# hsplit
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [133]:
# vsplit
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]